### ISSUE TITLE
Not compiling locally

### ISSUE THREAD

**Issue by infiniteluke** [iopipe/v8-profiler-lambda#3]
Hi! Thanks for sharing the awesome project!

I'm working on a project that depends on a project that depends on this package. When installing dependencies locally to develop, I'm unable to get this package to compile.
https://github.com/iopipe/v8-profiler-lambda/blob/87756746727531f2e94885d2e10074cd63eeaaaa/package.json#L34

As these compilation instructions are specific to AWS, I assume, what is the recommended way for using this locally on a machine that does not have a matching architecture?

## Error:
<details><pre><code>
[8/8] ⠁ v8-profiler-lambda: gyp: binding.gyp not found (cwd: /Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda) while trying
error /Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda: Command failed.
Exit code: 1
Command: node-pre-gyp install --target=4.8.0 --target_arch=x64 --target_platform=linux --fallback-to-build; node-pre-gyp install --target=6.10.0 --target_arch=x64 --target_platform=linux --fallback-to-build;
Arguments:
Directory: /Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@6.10.0 | darwin | x64
node-pre-gyp info check checked for "/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler/build/profiler/v5.7.1/node-v46-linux-x64/profiler.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/profiler/v5.7.1/node-v46-linux-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/profiler/v5.7.1/node-v46-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.1/node-v46-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-lambda@5.7.1 and node@4.8.0 (node-v46 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/profiler/v5.7.1/node-v46-linux-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.10.0 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.10.0 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/infiniteluke/.node-gyp/4.8.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/infiniteluke/.node-gyp/4.8.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/infiniteluke/.node-gyp/4.8.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/Users/infiniteluke/.nvm/versions/node/v6.10.0/bin/node" "/Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp/bin/node-gyp.js" "configure" "--target=4.8.0" "--target_arch=x64" "--target_platform=linux" "--fallback-to-build" "--module=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler/build/profiler/v5.7.1/node-v46-linux-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler/build/profiler/v5.7.1/node-v46-linux-x64"
gyp ERR! cwd /Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/infiniteluke/.nvm/versions/node/v6.10.0/bin/node /Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp/bin/node-gyp.js configure --target=4.8.0 --target_arch=x64 --target_platform=linux --fallback-to-build --module=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler/build/profiler/v5.7.1/node-v46-linux-x64/profiler.node --module_name=profiler --module_path=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler/build/profiler/v5.7.1/node-v46-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 17.3.0
node-pre-gyp ERR! command "/Users/infiniteluke/.nvm/versions/node/v6.10.0/bin/node" "/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda/node_modules/.bin/node-pre-gyp" "install" "--target=4.8.0" "--target_arch=x64" "--target_platform=linux" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda
node-pre-gyp ERR! node -v v6.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/Users/infiniteluke/.nvm/versions/node/v6.10.0/bin/node /Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp/bin/node-gyp.js configure --target=4.8.0 --target_arch=x64 --target_platform=linux --fallback-to-build --module=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler/build/profiler/v5.7.1/node-v46-linux-x64/profiler.node --module_name=profiler --module_path=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler/build/profiler/v5.7.1/node-v46-linux-x64' (1)
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@6.10.0 | darwin | x64
node-pre-gyp info check checked for "/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler/build/profiler/v5.7.1/node-v48-linux-x64/profiler.node" (not found)
node-pre-gyp http GET https://node-inspector.s3.amazonaws.com/profiler/v5.7.1/node-v48-linux-x64.tar.gz
node-pre-gyp http 404 https://node-inspector.s3.amazonaws.com/profiler/v5.7.1/node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/profiler/v5.7.1/node-v48-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-profiler-lambda@5.7.1 and node@6.10.0 (node-v48 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://node-inspector.s3.amazonaws.com/profiler/v5.7.1/node-v48-linux-x64.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.10.0 | darwin | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.10.0 | darwin | x64
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/infiniteluke/.node-gyp/6.10.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/infiniteluke/.node-gyp/6.10.0',
gyp info spawn args   '-Dnode_gyp_dir=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/infiniteluke/.node-gyp/6.10.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp: binding.gyp not found (cwd: /Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda) while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/Users/infiniteluke/.nvm/versions/node/v6.10.0/bin/node" "/Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp/bin/node-gyp.js" "configure" "--target=6.10.0" "--target_arch=x64" "--target_platform=linux" "--fallback-to-build" "--module=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler/build/profiler/v5.7.1/node-v48-linux-x64/profiler.node" "--module_name=profiler" "--module_path=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler/build/profiler/v5.7.1/node-v48-linux-x64"
gyp ERR! cwd /Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/infiniteluke/.nvm/versions/node/v6.10.0/bin/node /Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp/bin/node-gyp.js configure --target=6.10.0 --target_arch=x64 --target_platform=linux --fallback-to-build --module=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler/build/profiler/v5.7.1/node-v48-linux-x64/profiler.node --module_name=profiler --module_path=/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler/build/profiler/v5.7.1/node-v48-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 17.3.0
node-pre-gyp ERR! command "/Users/infiniteluke/.nvm/versions/node/v6.10.0/bin/node" "/Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda/node_modules/.bin/node-pre-gyp" "install" "--target=6.10.0" "--target_arch=x64" "--target_platform=linux" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/infiniteluke/code/nbc/ads-metadata/node_modules/v8-profiler-lambda
node-pre-gyp ERR! node -v v6.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/Users/infiniteluke/.nvm/versions/node/v6.10.0/bin/node /Users/infiniteluke/code/nbc/ads-metadata/node_modules/node-gyp/bin/node-gyp.js con
</pre></code></details>

## Machine Specs:
Node: 6.10.0
OS: macOS High Sierra
Machine: MacBook Pro (Retina, 13-inch, Early 2015)
Processor: 2.9 GHz Intel Core i5

**Comment by infiniteluke** [comment]
I have narrowed this down to my node version manager not correctly switch node version. 😢 

Thanks again!

**Comment by chasingmaxwell** [comment]
Glad you got it figured out! :)
